"""
Fine-tune ResNet-18 on the authentic-vs-counterfeit dataset.

Prerequisites:
    data/images/authentic/    — student-provided pack photos
    data/images/counterfeit/  — generated by scripts/prepare_image_dataset.py

Usage:
    cd backend
    python -m scripts.train_image                    # default 5 epochs
    python -m scripts.train_image --epochs 10 --batch 32

Approach:
    * Start from ImageNet-pretrained ResNet-18 (torchvision).
    * Replace the 1000-class fc layer with a 2-class head.
    * Freeze every layer except layer4 + fc — this is transfer
      learning; we only teach the top of the network how to separate
      our two classes, which works well with small datasets.
    * 80/20 train/val split, standard augmentation for generalisation.

Output: models_cache/image/resnet18_finetuned.pt — picked up
automatically by services/image_classifier.py on the next request.
"""

from __future__ import annotations

import argparse
import random
from pathlib import Path

import torch
import torch.nn as nn
import torch.optim as optim
from torch.utils.data import DataLoader, random_split
from torchvision import datasets, models, transforms

BACKEND_DIR = Path(__file__).resolve().parent.parent
DATA_DIR = BACKEND_DIR / "data" / "images"
OUTPUT_PATH = BACKEND_DIR / "models_cache" / "image" / "resnet18_finetuned.pt"

# torchvision's ImageFolder alphabetises class subfolders by default —
# "authentic" (a) comes before "counterfeit" (c), so 0 = authentic and
# 1 = counterfeit. This matches services/image_classifier.CLASS_NAMES.

IMAGENET_MEAN = [0.485, 0.456, 0.406]
IMAGENET_STD = [0.229, 0.224, 0.225]


def _build_transforms() -> tuple[transforms.Compose, transforms.Compose]:
    train_tf = transforms.Compose(
        [
            transforms.RandomResizedCrop(224, scale=(0.7, 1.0)),
            transforms.RandomHorizontalFlip(),
            transforms.ColorJitter(brightness=0.2, contrast=0.2, saturation=0.2),
            transforms.ToTensor(),
            transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
        ]
    )
    eval_tf = transforms.Compose(
        [
            transforms.Resize(256),
            transforms.CenterCrop(224),
            transforms.ToTensor(),
            transforms.Normalize(mean=IMAGENET_MEAN, std=IMAGENET_STD),
        ]
    )
    return train_tf, eval_tf


def _build_model() -> nn.Module:
    net = models.resnet18(weights=models.ResNet18_Weights.IMAGENET1K_V1)
    # Freeze everything except layer4 and fc.
    for name, param in net.named_parameters():
        if not (name.startswith("layer4") or name.startswith("fc")):
            param.requires_grad = False
    net.fc = nn.Linear(net.fc.in_features, 2)
    return net


def _epoch(model, loader, criterion, optimiser, device, *, train: bool) -> tuple[float, float]:
    model.train() if train else model.eval()
    total_loss, total_correct, total = 0.0, 0, 0
    with torch.set_grad_enabled(train):
        for x, y in loader:
            x, y = x.to(device), y.to(device)
            logits = model(x)
            loss = criterion(logits, y)
            if train:
                optimiser.zero_grad()
                loss.backward()
                optimiser.step()
            total_loss += float(loss.item()) * x.size(0)
            total_correct += int((logits.argmax(1) == y).sum().item())
            total += x.size(0)
    return total_loss / total, total_correct / total


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--epochs", type=int, default=5)
    parser.add_argument("--batch", type=int, default=16)
    parser.add_argument("--lr", type=float, default=1e-4)
    parser.add_argument("--seed", type=int, default=42)
    parser.add_argument("--val-split", type=float, default=0.2)
    args = parser.parse_args()

    random.seed(args.seed)
    torch.manual_seed(args.seed)

    if not (DATA_DIR / "authentic").is_dir() or not (DATA_DIR / "counterfeit").is_dir():
        raise SystemExit(
            f"Expected subfolders 'authentic/' and 'counterfeit/' under {DATA_DIR}.\n"
            f"Populate authentic/ and run scripts/prepare_image_dataset.py first."
        )

    train_tf, eval_tf = _build_transforms()
    full_train = datasets.ImageFolder(str(DATA_DIR), transform=train_tf)
    full_eval = datasets.ImageFolder(str(DATA_DIR), transform=eval_tf)
    if full_train.classes != ["authentic", "counterfeit"]:
        raise SystemExit(
            f"Unexpected class ordering {full_train.classes}; expected "
            f"['authentic', 'counterfeit']. Rename folders so the first "
            f"alphabetically is the authentic one."
        )

    n_total = len(full_train)
    n_val = max(1, int(n_total * args.val_split))
    n_train = n_total - n_val
    indices = list(range(n_total))
    random.shuffle(indices)
    train_idx, val_idx = indices[:n_train], indices[n_train:]

    train_ds = torch.utils.data.Subset(full_train, train_idx)
    val_ds = torch.utils.data.Subset(full_eval, val_idx)

    train_loader = DataLoader(train_ds, batch_size=args.batch, shuffle=True, num_workers=0)
    val_loader = DataLoader(val_ds, batch_size=args.batch, shuffle=False, num_workers=0)

    device = (
        "cuda"
        if torch.cuda.is_available()
        else "mps"
        if torch.backends.mps.is_available()
        else "cpu"
    )
    print(
        f"[train_image] device={device}, train={len(train_ds)}, val={len(val_ds)}, "
        f"classes={full_train.classes}"
    )

    model = _build_model().to(device)
    criterion = nn.CrossEntropyLoss()
    optimiser = optim.Adam(
        [p for p in model.parameters() if p.requires_grad], lr=args.lr
    )

    best_acc = 0.0
    for epoch in range(1, args.epochs + 1):
        train_loss, train_acc = _epoch(
            model, train_loader, criterion, optimiser, device, train=True
        )
        val_loss, val_acc = _epoch(
            model, val_loader, criterion, optimiser, device, train=False
        )
        print(
            f"[train_image] epoch {epoch}/{args.epochs}  "
            f"train_loss={train_loss:.4f} train_acc={train_acc:.3f}  "
            f"val_loss={val_loss:.4f} val_acc={val_acc:.3f}"
        )
        if val_acc > best_acc:
            best_acc = val_acc
            OUTPUT_PATH.parent.mkdir(parents=True, exist_ok=True)
            torch.save(model.state_dict(), OUTPUT_PATH)
            print(f"[train_image]   saved checkpoint (best val_acc={best_acc:.3f})")

    print(f"[train_image] Done. Best val_acc = {best_acc:.3f}")
    print(f"[train_image] Weights: {OUTPUT_PATH}")
    print(
        "[train_image] Restart uvicorn and the image endpoint will use "
        "these weights automatically."
    )


if __name__ == "__main__":
    main()
